# Site settings
title: "Software Design Spring 2017"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://sd17spring.github.io/" # the base hostname & protocol for your site
timezone: America/New_York
github_username:  olin-computing

collections:
  assignments:
    output: true
    permalink: /assignments/:path/
  days:
    output: true
    permalink: /day/:path/
  toolboxes:
    output: true
    permalink: /toolboxes/:path/

defaults:
  - scope:
      path: ""
      type: assignment
    values:
      layout: single
  - scope:
      path: ""
      type: assignments
    values:
      layout: single
  - scope:
      path: ""
      type: days
    values:
      layout: single

course:
  github_owner: sd17spring
  calendar_url: https://docs.google.com/spreadsheets/d/1AwW8O0UQmDItCDn7DnJbW40tY1HrDggt8pWpVqG-HiE/pubhtml?gid=0&amp;single=true&amp;widget=true&amp;headers=false
  piazza_url: 'https://piazza.com/olin/spring2017/engr2510'
  # flootbits_url: https://floobits.com/sd17spring
  entrance_survey_url: https://goo.gl/forms/6MsKDGVf5SGFyIg22
  # mid_course_feedback_survey_url: http://goo.gl/forms/n2L9ESBpCU
  # visualization_teaming_spreadsheet: https://docs.google.com/spreadsheets/d/1gPIOu22NUhF_qKQERgW3SVuFnC-rYKbUBxw43U7N7QQ/edit?usp=sharing
  # final_project_proposal_spreadsheet: https://docs.google.com/spreadsheets/d/1CwGwmxU_yvaH7iFTmoLtX4ehRtiwSls9nrcT_ GRWZN4/edit?usp=sharing
